server:
  port: 8080
spring:
  application:
    name: dm-user-consumer
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
# open hystrix
feign:
  hystrix:
    enabled: true
# modify Ribbon LoadBalance -> RandomRule
dm-user-provider:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalance.RandomRule