server:
  port: 7900
spring:
  application:
    name: dm-config-provider
  cloud:
    config:
      server:
        git:
          # clone springcloudlearning slow, so create new resp springcloudconfig for it
          # uri: https://github.com/kuku940/SpringCloudLearning.git
          # search-paths: /dm-env/dm-config-server/src/main/resources/config/
          uri: https://github.com/kuku940/springcloudconfig.git
          search-paths: /
          password: ${github.password}
          username: ${github.username}
          #default-label: master
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
