server:
  port: 7900
spring:
  application:
    name: dm-config-provider
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuku940/SpringCloudLearning.git
          username: ${github.username}
          password: ${github.password}
          search-paths: /dm-env/dm-config-server/src/main/resources/config/
          #default-label: master
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
