server:
  port: 9220
spring:
  application:
    name: dm-user-provider
  # zipkin config
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
logging:
  level: info