server:
  port: 9250
spring:
  application:
    name: dm-pay-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dm_pay?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
  # zipkin config
  zipkin:
    base-url: http://localhost:7800
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
mybatis:
  mapper-locations: classpath*:mapper/*.xml