server:
  port: 9040
spring:
  application:
    name: dm-item-consumer
  # redis config
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  aop:
    proxy-target-class: true
  # zipkin config
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true
