server:
  port: 9060
spring:
  application:
    name: dm-scheduler-consumer
  # zipkin config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true